-- generated by LazyWorkspacesBootstrap
-- test: nvim -u __OUT_DIR__/init.lua

vim.g.mapleader = "__MAPLEADER__"
vim.g.maplocalleader = "__MAPLOCALLEADER__"

-- Bootstrap lazy-workspaces.nvim
local lwpath = vim.fn.stdpath("data") .. "/lazy/lazy-workspaces.nvim"
if not (vim.uv or vim.loop).fs_stat(lwpath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/ivankozlovcodes/lazy-workspaces.nvim.git",
		lwpath,
	})
end
vim.opt.rtp:prepend(lwpath)

require("lazy-workspaces").setup({
	configs = {
		default = { url = "file://__OUT_DIR__" },
	},
	-- __SPECS__
})
