-- generated by LazyWorkspacesBootstrap --dev
-- test: nvim -u __OUT_DIR__/init.lua

vim.g.mapleader = "__MAPLEADER__"
vim.g.maplocalleader = "__MAPLOCALLEADER__"

vim.opt.rtp:prepend("__PLUGIN_ROOT__")

require("lazy-workspaces").setup({
	configs = {
		default = { url = "file://__OUT_DIR__" },
	},
	-- __SPECS__
})
