local M = {}

-- TODO: show before/after diff in a float before writing

local function detect_namespaces(lua_dir)
  local namespaces = {}
  for _, path in ipairs(vim.fn.glob(lua_dir .. "/*/init.lua", false, true)) do
    local ns = path:match("/([^/]+)/init%.lua$")
    if ns then
      namespaces[#namespaces + 1] = ns
    end
  end
  return namespaces
end

local function strip_lazy_init(lines, ns)
  local out = {}
  for _, line in ipairs(lines) do
    if not line:match('require%(["\']' .. ns .. '%.lazy_init["\']%)') then
      out[#out + 1] = line
    end
  end
  return out
end

local function wrap_in_setup(lines)
  while lines[#lines] == "" do
    lines[#lines] = nil
  end
  local out = { "local M = {}", "", "function M.setup()" }
  for _, line in ipairs(lines) do
    out[#out + 1] = line == "" and "" or "  " .. line
  end
  out[#out + 1] = "end"
  out[#out + 1] = ""
  out[#out + 1] = "return M"
  return out
end

local function transform_ns_init(ns_dir, ns)
  local path = ns_dir .. "/init.lua"
  local lines = vim.fn.readfile(path)
  for _, l in ipairs(lines) do
    if l:match("function M%.setup") then
      return "skipped (already wrapped)"
    end
  end
  lines = strip_lazy_init(lines, ns)
  lines = wrap_in_setup(lines)
  vim.fn.writefile(lines, path)
  return "wrapped"
end

local function disable_lazy_bootstrap_files(ns_dir)
  local moved = {}
  for _, path in ipairs(vim.fn.glob(ns_dir .. "/*.lua", false, true)) do
    local lines = vim.fn.readfile(path)
    for _, line in ipairs(lines) do
      if line:match('require%(["\']lazy["\']%)%.setup') then
        local bak = path .. ".bak"
        vim.fn.rename(path, bak)
        moved[#moved + 1] = vim.fn.fnamemodify(path, ":t") .. " → " .. vim.fn.fnamemodify(bak, ":t")
        break
      end
    end
  end
  return moved
end

local function rename_plugin_dir(ns_dir)
  local lazy_dir = ns_dir .. "/lazy"
  local plugins_dir = ns_dir .. "/plugins"
  if vim.fn.isdirectory(lazy_dir) == 1 then
    vim.fn.rename(lazy_dir, plugins_dir)
    return "lazy/ → plugins/"
  elseif vim.fn.isdirectory(plugins_dir) == 1 then
    return "plugins/ already exists"
  end
  return "no plugin dir"
end

local function write_root_init(out_dir, namespaces)
  local leader = vim.g.mapleader or "\\"
  local localleader = vim.g.maplocalleader or "\\"
  local function q(v)
    return v == "\\" and '"\\\\"' or '"' .. v .. '"'
  end

  local enable_items = {}
  for _, ns in ipairs(namespaces) do
    enable_items[#enable_items + 1] = '"' .. ns .. '"'
  end

  local lines = {
    "-- generated by LazyWorkspacesBootstrap",
    "-- test: nvim -u " .. out_dir .. "/init.lua",
    "",
    "-- workspace root (set by LazyWorkspacesBootstrap)",
    'local workspace_root = "' .. out_dir .. '"',
    "",
    "vim.g.mapleader = " .. q(leader),
    "vim.g.maplocalleader = " .. q(localleader),
    "",
    "-- Bootstrap lazy.nvim",
    'local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"',
    "if not (vim.uv or vim.loop).fs_stat(lazypath) then",
    "  vim.fn.system({",
    '    "git", "clone", "--filter=blob:none", "--branch=stable",',
    '    "https://github.com/folke/lazy.nvim.git", lazypath,',
    "  })",
    "end",
    "vim.opt.rtp:prepend(lazypath)",
    "",
    "-- Bootstrap lazy-workspaces",
    'local lwpath = vim.fn.stdpath("data") .. "/lazy/lazy-workspaces.nvim"',
    "if not (vim.uv or vim.loop).fs_stat(lwpath) then",
    "  vim.fn.system({",
    '    "git", "clone", "--filter=blob:none",',
    '    "https://github.com/ivankozlovcodes/lazy-workspaces.nvim.git", lwpath,',
    "  })",
    "end",
    "vim.opt.rtp:prepend(lwpath)",
    "",
    "local workspace_specs = {}",
    "if (vim.uv or vim.loop).fs_stat(lwpath) then",
    '  workspace_specs = require("lazy-workspaces").collect({',
    "    workspaces = {",
    "      {",
    '        url = "file://" .. workspace_root,',
    "        enable = { " .. table.concat(enable_items, ", ") .. " },",
    "      },",
    "    },",
    "  })",
    "end",
    "",
    'require("lazy").setup({',
    "  spec = vim.list_extend(workspace_specs, {",
    '    { "ivankozlovcodes/lazy-workspaces.nvim", opts = {} },',
    "  }),",
    "  change_detection = { notify = false },",
    "})",
  }
  vim.fn.writefile(lines, out_dir .. "/init.lua")
end

---@param args {args: string}
function M.command(args)
  local parts = vim.split(args.args, "%s+", { trimempty = true })
  local src_dir, out_dir

  if #parts == 0 then
    src_dir = vim.fn.stdpath("config")
    out_dir = "/tmp/nvim"
  elseif #parts == 1 then
    src_dir = vim.fn.expand(parts[1])
    out_dir = "/tmp/nvim"
  else
    src_dir = vim.fn.expand(parts[1])
    out_dir = vim.fn.expand(parts[2])
  end

  src_dir = vim.fn.fnamemodify(src_dir, ":p"):gsub("/$", "")
  out_dir = vim.fn.fnamemodify(out_dir, ":p"):gsub("/$", "")

  if vim.fn.isdirectory(src_dir) == 0 then
    vim.notify("[lazy-workspaces] src not found: " .. src_dir, vim.log.levels.ERROR)
    return
  end

  local confirm = vim.fn.confirm(
    string.format("lazy-workspaces bootstrap\n\n  src: %s\n  out: %s\n\nCopy src → out and rewrite files. Proceed?", src_dir, out_dir),
    "&Yes\n&No", 2
  )
  if confirm ~= 1 then
    vim.notify("[lazy-workspaces] bootstrap cancelled", vim.log.levels.INFO)
    return
  end

  vim.fn.mkdir(out_dir, "p")
  local cp_out = vim.fn.system({ "cp", "-r", src_dir .. "/.", out_dir })
  if vim.v.shell_error ~= 0 then
    vim.notify("[lazy-workspaces] copy failed: " .. cp_out, vim.log.levels.ERROR)
    return
  end

  local lua_dir = out_dir .. "/lua"
  if vim.fn.isdirectory(lua_dir) == 0 then
    vim.notify("[lazy-workspaces] no lua/ dir in source", vim.log.levels.ERROR)
    return
  end

  local namespaces = detect_namespaces(lua_dir)
  if #namespaces == 0 then
    vim.notify("[lazy-workspaces] no namespaces found under lua/", vim.log.levels.ERROR)
    return
  end

  local results = {}
  for _, ns in ipairs(namespaces) do
    local ns_dir = lua_dir .. "/" .. ns
    local plugin_res = rename_plugin_dir(ns_dir)
    local init_res = transform_ns_init(ns_dir, ns)
    local moved = disable_lazy_bootstrap_files(ns_dir)
    local moved_res = #moved > 0 and ("moved: " .. table.concat(moved, ", ")) or "no lazy bootstrap files"
    results[#results + 1] = ns .. ": plugins(" .. plugin_res .. "), init(" .. init_res .. "), " .. moved_res
  end

  write_root_init(out_dir, namespaces)
  results[#results + 1] = "wrote init.lua"

  local msg = "[lazy-workspaces] bootstrap → " .. out_dir .. "\n"
  for _, r in ipairs(results) do
    msg = msg .. "  • " .. r .. "\n"
  end
  msg = msg .. "\nTest: nvim -u " .. out_dir .. "/init.lua"
  vim.notify(msg, vim.log.levels.INFO)
end

return M
