local M = {}

-- TODO: show before/after diff in a float before writing

local detect_workspaces = require("lazy-workspaces").detect_workspaces

local function strip_lazy_init(lines, ns)
  local mod_name = ns:gsub("/", ".")  -- slash names → dot notation for require() pattern
  local out = {}
  for _, line in ipairs(lines) do
    if not line:match('require%(["\']' .. mod_name .. '%.lazy_init["\']%)') then
      out[#out + 1] = line
    end
  end
  return out
end

local function wrap_in_setup(lines)
  while lines[#lines] == "" do
    lines[#lines] = nil
  end
  local out = { "local M = {}", "", "function M.setup()" }
  for _, line in ipairs(lines) do
    out[#out + 1] = line == "" and "" or "  " .. line
  end
  out[#out + 1] = "end"
  out[#out + 1] = ""
  out[#out + 1] = "return M"
  return out
end

local function transform_ns_init(ns_dir, ns)
  local path = ns_dir .. "/init.lua"
  local lines = vim.fn.readfile(path)
  for _, l in ipairs(lines) do
    if l:match("function M%.setup") then
      return "skipped (already wrapped)"
    end
  end
  lines = strip_lazy_init(lines, ns)
  lines = wrap_in_setup(lines)
  vim.fn.writefile(lines, path)
  return "wrapped"
end

local function migrate_flat_plugins(lua_dir)
  local plugins_dir = lua_dir .. "/plugins"
  local specs_dir   = plugins_dir .. "/plugins"
  local init_path   = plugins_dir .. "/init.lua"
  local init_exists = vim.fn.filereadable(init_path) == 1

  vim.fn.mkdir(specs_dir, "p")
  local moved = {}
  for _, path in ipairs(vim.fn.glob(plugins_dir .. "/*.lua", false, true)) do
    local fname = vim.fn.fnamemodify(path, ":t")
    if fname ~= "init.lua" then
      vim.fn.rename(path, specs_dir .. "/" .. fname)
      moved[#moved + 1] = fname
    end
  end

  if init_exists then
    vim.notify("[lazy-workspaces] lua/plugins/init.lua already exists, skipping generation", vim.log.levels.WARN)
  else
    vim.fn.writefile({ "local M = {}", "", "function M.setup() end", "", "return M" }, init_path)
  end

  if #moved > 0 then
    vim.notify(
      "[lazy-workspaces] lua/plugins/*.lua moved to lua/plugins/plugins/. "
        .. 'If any spec file required another by name, update to require("plugins.plugins.X").',
      vim.log.levels.WARN
    )
  end

  return moved
end

local function write_config_init(config_dir)
  local init_path = config_dir .. "/init.lua"
  if vim.fn.filereadable(init_path) == 1 then
    vim.notify("[lazy-workspaces] lua/config/init.lua already exists, skipping generation", vim.log.levels.WARN)
    return "skipped"
  end

  local requires = {}
  for _, f in ipairs(vim.fn.glob(config_dir .. "/*.lua", false, true)) do
    local stem = vim.fn.fnamemodify(f, ":t:r")
    requires[#requires + 1] = '  require("config.' .. stem .. '")'
  end

  local lines = { "local M = {}", "", "function M.setup()" }
  vim.list_extend(lines, requires)
  vim.list_extend(lines, { "end", "", "return M" })
  vim.fn.writefile(lines, init_path)
  return "written"
end

local function disable_lazy_bootstrap_files(ns_dir)
  local moved = {}
  for _, path in ipairs(vim.fn.glob(ns_dir .. "/*.lua", false, true)) do
    local lines = vim.fn.readfile(path)
    for _, line in ipairs(lines) do
      if line:match('require%(["\']lazy["\']%)%.setup') then
        local bak = path .. ".bak"
        vim.fn.rename(path, bak)
        moved[#moved + 1] = vim.fn.fnamemodify(path, ":t") .. " → " .. vim.fn.fnamemodify(bak, ":t")
        break
      end
    end
  end
  return moved
end

local function rename_plugin_dir(ns_dir)
  local lazy_dir = ns_dir .. "/lazy"
  local plugins_dir = ns_dir .. "/plugins"
  if vim.fn.isdirectory(lazy_dir) == 1 then
    vim.fn.rename(lazy_dir, plugins_dir)
    return "lazy/ → plugins/"
  elseif vim.fn.isdirectory(plugins_dir) == 1 then
    return "plugins/ already exists"
  end
  return "no plugin dir"
end

local function write_root_init(out_dir)
  local leader = vim.g.mapleader or "\\"
  local localleader = vim.g.maplocalleader or "\\"
  local function q(v)
    return v == "\\" and '"\\\\"' or '"' .. v .. '"'
  end

  local lines = {
    "-- generated by LazyWorkspacesBootstrap",
    "-- test: nvim -u " .. out_dir .. "/init.lua",
    "",
    "-- workspace root (set by LazyWorkspacesBootstrap)",
    'local workspace_root = "' .. out_dir .. '"',
    "",
    "vim.g.mapleader = " .. q(leader),
    "vim.g.maplocalleader = " .. q(localleader),
    "",
    "-- Bootstrap lazy-workspaces.nvim",
    'local lwpath = vim.fn.stdpath("data") .. "/lazy/lazy-workspaces.nvim"',
    "if not (vim.uv or vim.loop).fs_stat(lwpath) then",
    "  vim.fn.system({",
    '    "git", "clone", "--filter=blob:none",',
    '    "https://github.com/ivankozlovcodes/lazy-workspaces.nvim.git", lwpath,',
    "  })",
    "end",
    "vim.opt.rtp:prepend(lwpath)",
    "",
    'require("lazy-workspaces").setup({',
    "  configs = {",
    "    {",
    '      url = "file://" .. workspace_root,',
    "    },",
    "  },",
    "})",
  }
  vim.fn.writefile(lines, out_dir .. "/init.lua")
end

---@param args {args: string}
function M.command(args)
  local parts = vim.split(args.args, "%s+", { trimempty = true })
  local src_dir, out_dir

  if #parts == 0 then
    src_dir = vim.fn.stdpath("config")
    out_dir = "/tmp/nvim"
  elseif #parts == 1 then
    src_dir = vim.fn.expand(parts[1])
    out_dir = "/tmp/nvim"
  else
    src_dir = vim.fn.expand(parts[1])
    out_dir = vim.fn.expand(parts[2])
  end

  src_dir = vim.fn.fnamemodify(src_dir, ":p"):gsub("/$", "")
  out_dir = vim.fn.fnamemodify(out_dir, ":p"):gsub("/$", "")

  if vim.fn.isdirectory(src_dir) == 0 then
    vim.notify("[lazy-workspaces] src not found: " .. src_dir, vim.log.levels.ERROR)
    return
  end

  local confirm = vim.fn.confirm(
    string.format(
      "lazy-workspaces bootstrap\n\n  src: %s\n  out: %s\n\nCopy src → out and rewrite files. Proceed?",
      src_dir,
      out_dir
    ),
    "&Yes\n&No",
    2
  )
  if confirm ~= 1 then
    vim.notify("[lazy-workspaces] bootstrap cancelled", vim.log.levels.INFO)
    return
  end

  vim.fn.mkdir(out_dir, "p")
  local cp_out = vim.fn.system({ "cp", "-r", src_dir .. "/.", out_dir })
  if vim.v.shell_error ~= 0 then
    vim.notify("[lazy-workspaces] copy failed: " .. cp_out, vim.log.levels.ERROR)
    return
  end

  local lua_dir = out_dir .. "/lua"
  if vim.fn.isdirectory(lua_dir) == 0 then
    vim.notify("[lazy-workspaces] no lua/ dir in source", vim.log.levels.ERROR)
    return
  end

  local namespaces = detect_workspaces(lua_dir)
  local results = {}

  if #namespaces == 0 then
    local has_plugins = vim.fn.isdirectory(lua_dir .. "/plugins") == 1
    local has_config  = vim.fn.isdirectory(lua_dir .. "/config") == 1

    if not has_plugins and not has_config then
      vim.notify("[lazy-workspaces] no namespaces found under lua/", vim.log.levels.ERROR)
      return
    end

    if has_plugins then
      local moved = migrate_flat_plugins(lua_dir)
      results[#results + 1] = "plugins: moved specs(" .. #moved .. " files)"
    end
    if has_config then
      local res = write_config_init(lua_dir .. "/config")
      results[#results + 1] = "config: init(" .. res .. ")"
    end

    local loose = vim.fn.glob(lua_dir .. "/*.lua", false, true)
    if #loose > 0 then
      local names = {}
      for _, f in ipairs(loose) do names[#names + 1] = vim.fn.fnamemodify(f, ":t") end
      vim.notify(
        "[lazy-workspaces] orphaned files in lua/ not claimed by any workspace: " .. table.concat(names, ", "),
        vim.log.levels.WARN
      )
    end

    if has_config  then namespaces[#namespaces + 1] = "config"  end
    if has_plugins then namespaces[#namespaces + 1] = "plugins" end

    disable_lazy_bootstrap_files(out_dir)
  else
    for _, ns in ipairs(namespaces) do
      local ns_dir = lua_dir .. "/" .. ns
      local plugin_res = rename_plugin_dir(ns_dir)
      local init_res = transform_ns_init(ns_dir, ns)
      local moved = disable_lazy_bootstrap_files(ns_dir)
      local moved_res = #moved > 0 and ("moved: " .. table.concat(moved, ", ")) or "no lazy bootstrap files"
      results[#results + 1] = ns .. ": plugins(" .. plugin_res .. "), init(" .. init_res .. "), " .. moved_res
    end
  end

  write_root_init(out_dir)
  results[#results + 1] = "wrote init.lua"

  local msg = "[lazy-workspaces] bootstrap → " .. out_dir .. "\n"
  for _, r in ipairs(results) do
    msg = msg .. "  • " .. r .. "\n"
  end
  msg = msg .. "\nTest: nvim -u " .. out_dir .. "/init.lua"
  vim.notify(msg, vim.log.levels.INFO)
end

M._test = {
  detect_workspaces = detect_workspaces,
  strip_lazy_init = strip_lazy_init,
  wrap_in_setup = wrap_in_setup,
  transform_ns_init = transform_ns_init,
  disable_lazy_bootstrap_files = disable_lazy_bootstrap_files,
  rename_plugin_dir = rename_plugin_dir,
  write_root_init = write_root_init,
  migrate_flat_plugins = migrate_flat_plugins,
  write_config_init = write_config_init,
}

return M
